Document: webdis
Title: Debian webdis Manual
Author: <insert document author here>
Abstract: This manual describes what webdis is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/webdis/webdis.sgml.gz

Format: postscript
Files: /usr/share/doc/webdis/webdis.ps.gz

Format: text
Files: /usr/share/doc/webdis/webdis.text.gz

Format: HTML
Index: /usr/share/doc/webdis/html/index.html
Files: /usr/share/doc/webdis/html/*.html
